sonar.projectKey = iperez13_Implementaci-n-de-SAST-con-SonarQube 
sonar.projectName=Secure Audit Lab
sonar.projectVersion=1.0.0

# Organización de SonarCloud
sonar.organization = iperez13
sonar.host.url=https://sonarcloud.io

# ========================================
# FUENTES DE CÓDIGO
# ========================================
sonar.sources=.
sonar.inclusions=**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.exclusions=node_modules/**,.*/**,**/*.spec.js,**/*.test.js,.git/**,logs/**,dist/**,build/**,coverage/**
sonar.sourceEncoding=UTF-8

# ========================================
# CONFIGURACIÓN DE JAVASCRIPT
# ========================================
sonar.javascript.file.suffixes=.js,.jsx
sonar.typescript.file.suffixes=.ts,.tsx

# ========================================
# IMPORTAR REPORTES EXTERNOS
# ========================================
# Usar formato genérico de SonarQube
sonar.externalIssuesReportPaths=eslint-report.json,vulnerabilities-report.json

# ========================================
# SEGURIDAD
# ========================================
sonar.security.hotspots.enabled=true

# ========================================
# COBERTURA
# ========================================
sonar.coverage.exclusions=node_modules/**,**/*.test.js,**/*.spec.js